### ISSUE TITLE
Downloading the source is broken, due to change in the github security policy.

### ISSUE THREAD

**Issue by iGormilhit** [bartoszek/AUR-openboard-git#1]
The build fails even before beginning as the source can't be downloaded. The following line result in a error:

https://github.com/bartoszek/AUR-openboard-git/blob/8447ee94dfb78ad03ba3233242c23cf695f25f48/PKGBUILD#L19

The error is:

```
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
 ```
 And there's a link to <https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git>
 
 In the `PKGBUILD` of the [AUR-openboard](https://github.com/bartoszek/AUR-openboard) project, the github URL is in https and not SSH, thus allowing the build to download the source:
 <https://github.com/bartoszek/AUR-openboard/blob/master/PKGBUILD#L15>

**Comment by bartoszek** [comment]
Thanks for the early warning.
btw. run a quick scan over all AUR packages and looks like ~3k is using `git://github.com` in the sources, are you predicting a massive blowout of those packages at march 15 ಥ_ಥ
http://ix.io/3MSY
